/**
 * Solver integration tests against the real Nullius game-data export.
 *
 * Each test loads a pre-traced chain fixture from src/solver/__fixtures__/
 * and runs the full solver pipeline.  The fixtures were generated by:
 *
 *   node scripts/trace-recipe-chain.js data/samples/nullius/game-data.json \
 *        <itemId>:<rate> --md spec/solver-chains/<name>.md \
 *        > src/solver/__fixtures__/<name>.fixture.json
 *
 * Human-readable chain documentation lives in spec/solver-chains/.
 *
 * The game-data file is git-ignored (too large).  All tests skip automatically
 * when the file is absent so CI passes without it.  Run locally after
 * re-exporting from Factorio to catch regressions.
 *
 * To add a new chain:
 *   1. Run the trace script (see spec/solver-chains/README.md).
 *   2. Add a describe() block below following the existing pattern.
 *   3. Commit the .md and .fixture.json files alongside this test.
 */

import { describe, it, expect, beforeAll } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { loadGameDataFromJson } from '../../data/loader'
import { solve } from './index'
import type { GameData, RecipeNode, SolverResult } from '../../data/types'

// ---------------------------------------------------------------------------
// Game data loading (shared across all chains in this file)
// ---------------------------------------------------------------------------

const SAMPLE_PATH = resolve(
  import.meta.dirname,
  '../../data/samples/nullius/game-data.json',
)

const sampleExists = existsSync(SAMPLE_PATH)

let gameData: GameData

// ---------------------------------------------------------------------------
// Fixture type
// ---------------------------------------------------------------------------

/** Shape of the JSON files in src/solver/__fixtures__/. */
interface SolverChainFixture {
  description: string
  goals: { id: string; itemId: string; rate: number }[]
  nodes: {
    id: string
    recipeId: string
    modules: []
    byproductPolicy: Record<string, 'discard' | 'feed-back'>
  }[]
}

function loadFixture(name: string): SolverChainFixture {
  const path = resolve(import.meta.dirname, `../__fixtures__/${name}.fixture.json`)
  return JSON.parse(readFileSync(path, 'utf-8')) as SolverChainFixture
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a minimal plan from a fixture and loaded game data. */
function buildPlan(fixture: SolverChainFixture, _gd: GameData): { goals: SolverChainFixture['goals']; nodes: RecipeNode[] } {
  return {
    goals: fixture.goals,
    // Fixture JSON pre-dates the discriminated union; inject kind at runtime.
    nodes: fixture.nodes.map(n => ({ kind: 'game-recipe' as const, ...n })) as RecipeNode[],
  }
}

/** Run the solver for a fixture and return the result. */
function runChain(fixture: SolverChainFixture, gd: GameData): SolverResult {
  return solve(buildPlan(fixture, gd), gd)
}

// ---------------------------------------------------------------------------
// Standard assertions applied to every chain
// ---------------------------------------------------------------------------

/**
 * Core contract that every successfully traced chain must satisfy:
 *   1. solve() does not throw.
 *   2. Every goal item is produced by at least one SolvedNode.
 *   3. No 'no-recipe' warning is emitted for a goal item.
 *   4. Every solved node's throughput is positive (solver found a real solution).
 */
function assertChainSolves(fixture: SolverChainFixture, gd: GameData): SolverResult {
  const result = runChain(fixture, gd)

  // 1. At least one node was solved.
  expect(result.nodes.length).toBeGreaterThan(0)

  // 2. Every goal item appears in at least one node's output rates.
  for (const goal of fixture.goals) {
    const produced = result.nodes.some(n => goal.itemId in n.outputRates)
    expect(produced, `Goal item '${goal.itemId}' is not produced by any solved node`).toBe(true)
  }

  // 3. No missing-recipe warnings for goal items.
  const goalIds = new Set(fixture.goals.map(g => g.itemId))
  const noRecipeForGoal = result.warnings.filter(
    w => w.type === 'no-recipe' && goalIds.has((w as { itemId: string }).itemId),
  )
  expect(
    noRecipeForGoal,
    `Unexpected 'no-recipe' warnings for goal items: ${noRecipeForGoal.map(w => (w as { itemId: string }).itemId).join(', ')}`,
  ).toHaveLength(0)

  // 4. All solved throughputs are positive.
  for (const n of result.nodes) {
    expect(
      n.throughput,
      `Node '${n.recipeNodeId}' has non-positive throughput (${n.throughput})`,
    ).toBeGreaterThan(0)
  }

  return result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe.skipIf(!sampleExists)('solver integration — Nullius game data', () => {
  beforeAll(() => {
    gameData = loadGameDataFromJson(readFileSync(SAMPLE_PATH, 'utf-8'))
  })

  // ── automation-science-pack ──────────────────────────────────────────────
  // 4-node chain: assembler, gear wheel, copper plate, iron plate.
  // Iron/copper ore are cycle targets → treated as raw external inputs.
  // Good sanity check that the basic pipeline works end-to-end.

  describe('automation-science-pack — 60/min', () => {
    let fixture: SolverChainFixture

    beforeAll(() => {
      fixture = loadFixture('automation-science-pack')
    })

    it('passes standard chain assertions', () => {
      assertChainSolves(fixture, gameData)
    })

    it('solves all plan nodes (4 recipe nodes → 4 solved nodes)', () => {
      const result = runChain(fixture, gameData)
      expect(result.nodes).toHaveLength(fixture.nodes.length)
    })

    it('produces automation-science-pack at 60/min', () => {
      const result = runChain(fixture, gameData)
      const node = result.nodes.find(n => 'automation-science-pack' in n.outputRates)
      expect(node).toBeDefined()
      // Recipe yields 1× per craft at 5s; goal is 60/min.
      expect(node!.outputRates['automation-science-pack']).toBeCloseTo(60, 0)
    })

    it('has no solver warnings', () => {
      const result = runChain(fixture, gameData)
      expect(result.warnings).toHaveLength(0)
    })
  })

  // ── chemical-science-pack ────────────────────────────────────────────────
  // 13-node chain; raw input: coal (via basic-oil-processing).
  // Exercises oil processing, plastic, advanced circuits, engine units.

  describe('chemical-science-pack — 60/min', () => {
    let fixture: SolverChainFixture

    beforeAll(() => {
      fixture = loadFixture('chemical-science-pack')
    })

    it('passes standard chain assertions', () => {
      assertChainSolves(fixture, gameData)
    })

    it('produces chemical-science-pack at 60/min', () => {
      const result = runChain(fixture, gameData)
      const node = result.nodes.find(n => 'chemical-science-pack' in n.outputRates)
      expect(node).toBeDefined()
      // Recipe yields 2× per craft; goal is 60/min → throughput ≈ 30 crafts/min.
      expect(node!.outputRates['chemical-science-pack']).toBeCloseTo(60, 0)
    })

    it('consumes coal as a raw resource (unsatisfied item)', () => {
      const result = runChain(fixture, gameData)
      const coal = result.unsatisfied.find(u => u.itemId === 'coal')
      expect(coal, 'coal should appear in unsatisfied raw inputs').toBeDefined()
      expect(coal!.rate).toBeGreaterThan(0)
    })
  })

  // ── logistic-science-pack ────────────────────────────────────────────────
  // 10-node Nullius chain: motors, rods, gears, plates, ingots.
  // Iron ore is a cycle target → treated as raw external input.

  describe('logistic-science-pack — 60/min', () => {
    let fixture: SolverChainFixture

    beforeAll(() => {
      fixture = loadFixture('logistic-science-pack')
    })

    it('passes standard chain assertions', () => {
      assertChainSolves(fixture, gameData)
    })

    it('produces logistic-science-pack at 60/min', () => {
      const result = runChain(fixture, gameData)
      const node = result.nodes.find(n => 'logistic-science-pack' in n.outputRates)
      expect(node).toBeDefined()
      expect(node!.outputRates['logistic-science-pack']).toBeCloseTo(60, 0)
    })
  })
})
